// skillIcons.ts
import { IoLogoJavascript, IoLogoNodejs } from "react-icons/io";
import {
  SiExpress,
  SiMongodb,
  SiPrisma,
  SiRazorpay,
  SiShadcnui,
  SiTailwindcss,
  SiPostman,
  SiZod,
  SiDocker,
  SiNginx,
  SiAmazon,
  SiGooglecloud,
  SiTypescript,
  SiSocketdotio,
  SiStripe,
  SiGit,
  SiGithub,
  SiGitlab,
} from "react-icons/si";
import { IconType } from "react-icons";
import { FaBootstrap, FaCss3, FaHtml5, FaReact } from "react-icons/fa";
import { DiRedis } from "react-icons/di";
import { TbBrandNextjs, TbBrandRedux } from "react-icons/tb";
import { BiLogoPostgresql } from "react-icons/bi";
import { MdSchema } from "react-icons/md"; // placeholder for clean architecture
import { BsDiagram3 } from "react-icons/bs"; // placeholder for repo pattern

export const skillIcons: Record<string, IconType> = {
  Html: FaHtml5,
  Css: FaCss3,
  Bootstrap: FaBootstrap,
  Javascript: IoLogoJavascript,
  Typescript: SiTypescript,
  Nodejs: IoLogoNodejs,
  Express: SiExpress,
  Mongodb: SiMongodb,
  React: FaReact,
  NextJs: TbBrandNextjs,
  TailWind: SiTailwindcss,
  "shadcn/ui": SiShadcnui,
  Redux: TbBrandRedux,
  RazortPayGateWay: SiRazorpay,
  PostgreSQL: BiLogoPostgresql,
  Prisma: SiPrisma,
  Redis: DiRedis,
  Docker: SiDocker,
  Nginx: SiNginx,
  AWS: SiAmazon,
  GoogleCloud: SiGooglecloud,
  Zod: SiZod,
  SocketIO: SiSocketdotio,
  Stripe: SiStripe,
  Git: SiGit,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Postman: SiPostman,
  CleanArchitecture: MdSchema,
  RepositoryPattern: BsDiagram3,
};

export const skillColors: Record<string, string> = {
  Html: "#e34c26",
  Css: "#264de4",
  Bootstrap: "#7F0AF9",
  Javascript: "#f7df1e",
  Typescript: "#3178c6",
  Nodejs: "#68a063",
  Express: "#e6e6e6",
  Mongodb: "#4DB33D",
  React: "#61dafb",
  NextJs: "white",
  TailWind: "#4c31f7",
  "shadcn/ui": "white",
  Redux: "#7248B7",
  RazortPayGateWay: "#02042b",
  PostgreSQL: "#335F84",
  Prisma: "#0B344B",
  Redis: "#d82c20",
  Docker: "#0db7ed",
  Nginx: "#269539",
  AWS: "#FF9900",
  GoogleCloud: "#4285F4",
  Zod: "#3c3c3c",
  SocketIO: "#010101",
  Stripe: "#635bff",
  Git: "#f1502f",
  GitHub: "#333",
  GitLab: "#e24329",
  Postman: "#ff6c37",
  CleanArchitecture: "#6a0dad",
  RepositoryPattern: "#0088cc",
};
